### ISSUE TITLE
Support for offheap Arrays in @data-classes

### ISSUE THREAD

**Issue by flock0** [densh/scala-offheap#24]
I have been trying to use offheap Arrays as fields in @data-classes, for example:
`@data class Blah(arr: Array[Int])`

Currently I receive the following error message when trying to do that:
```
.../Test.scala:4: exception during macro expansion: 
[error] scala.MatchError: offheap.x64.Array[Int] (of class scala.reflect.internal.Types$ClassArgsTypeRef)
[error] 	at offheap.internal.macros.Common$class.read(Common.scala:108)
[error] 	at offheap.internal.macros.Method.read(Method.scala:7)
[error] 	at offheap.internal.macros.Method$$anonfun$accessor$1.applyOrElse(Method.scala:29)
[error] 	at offheap.internal.macros.Method$$anonfun$accessor$1.applyOrElse(Method.scala:25)
[error] 	at scala.PartialFunction$$anonfun$runWith$1.apply(PartialFunction.scala:141)
[error] 	at scala.PartialFunction$$anonfun$runWith$1.apply(PartialFunction.scala:140)
[error] 	at scala.collection.Iterator$class.foreach(Iterator.scala:750)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1202)
[error] 	at scala.collection.TraversableOnce$class.collectFirst(TraversableOnce.scala:132)
[error] 	at scala.collection.AbstractTraversable.collectFirst(Traversable.scala:104)
[error] 	at offheap.internal.macros.Method.accessor(Method.scala:25)
[error]     @data class Blah(arr: Array[Int])
[error]      ^
[error] one error found
```

**Comment by densh** [comment]
Thanks for the bug report, I'll have a look at it today.

**Comment by amirsh** [comment]
:+1:
